name: "Run stylelint with reviewdog"
description: "🐶 Run stylelint with reviewdog on pull requests to improve code review experience."
author: "haya14busa (reviewdog)"
inputs:
  github_token:
    description: "GITHUB_TOKEN."
    required: true
  level:
    description: "Report level for reviewdog [info,warning,error]"
    default: "error"
    required: false
  directory:
    description: "The subdirectory to execute the action in."
    default: "."
    required: false
  reporter:
    description: |
      Reporter of reviewdog command [github-pr-check,github-pr-review,github-check].
      Default is github-pr-check.
      github-pr-review can use Markdown and add a link to rule page in reviewdog reports.
    default: "github-pr-check"
    required: false
  stylelint_input:
    description: "Files or glob. Default: `**/*.css`.  It's same as `[input]` of stylelint."
    default: "**/*.css"
    required: false
  stylelint_config:
    description: "It's same as `--config` flag of stylelint."
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "alert-triangle"
  color: "yellow"
